"""новая миграция 2

Revision ID: 09c60d7beafa
Revises: ef5934af6235
Create Date: 2025-02-14 17:56:30.449615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09c60d7beafa'
down_revision: Union[str, None] = 'ef5934af6235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('pagelinks_path_localecode_index', table_name='pageLinks')
    op.drop_table('pageLinks')
    op.drop_table('assetData')
    op.drop_table('searchEngines')
    op.drop_table('brute')
    op.drop_table('groups')
    op.drop_table('assets')
    op.drop_table('storage')
    op.drop_table('authentication')
    op.drop_table('pageHistory')
    op.drop_index('sessions_expired_index', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('pageTree')
    op.drop_table('pages')
    op.drop_table('apiKeys')
    op.drop_table('pageTags')
    op.drop_table('loggers')
    op.drop_table('renderers')
    op.drop_table('analytics')
    op.drop_table('migrations_lock')
    op.drop_table('userGroups')
    op.drop_table('navigation')
    op.drop_table('users')
    op.drop_table('locales')
    op.drop_table('migrations')
    op.drop_table('commentProviders')
    op.drop_table('userKeys')
    op.drop_table('settings')
    op.drop_table('tags')
    op.drop_table('assetFolders')
    op.drop_table('userAvatars')
    op.drop_table('pageHistoryTags')
    op.drop_column('user', 'theme_rules')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('theme_rules', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_table('pageHistoryTags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pageId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tagId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pageId'], ['pageHistory.id'], name='pagehistorytags_pageid_foreign', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tagId'], ['tags.id'], name='pagehistorytags_tagid_foreign', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pageHistoryTags_pkey')
    )
    op.create_table('userAvatars',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='userAvatars_pkey')
    )
    op.create_table('assetFolders',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"assetFolders_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('parentId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parentId'], ['assetFolders.id'], name='assetfolders_parentid_foreign'),
    sa.PrimaryKeyConstraint('id', name='assetFolders_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tags_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('tag', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('createdAt', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('updatedAt', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tags_pkey'),
    sa.UniqueConstraint('tag', name='tags_tag_unique'),
    postgresql_ignore_search_path=False
    )
    op.create_table('settings',
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('updatedAt', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name='settings_pkey')
    )
    op.create_table('userKeys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('createdAt', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('validUntil', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='userkeys_userid_foreign'),
    sa.PrimaryKeyConstraint('id', name='userKeys_pkey')
    )
    op.create_table('commentProviders',
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('isEnabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name='commentProviders_pkey')
    )
    op.create_table('migrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('batch', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('migration_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='migrations_pkey')
    )
    op.create_table('locales',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='locales_pkey')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('providerId', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tfaIsActive', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('tfaSecret', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('jobTitle', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('pictureUrl', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=255), server_default=sa.text("'America/New_York'::character varying"), autoincrement=False, nullable=False),
    sa.Column('isSystem', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('isActive', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('isVerified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('mustChangePwd', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('createdAt', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('updatedAt', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('providerKey', sa.VARCHAR(length=255), server_default=sa.text("'local'::character varying"), autoincrement=False, nullable=False),
    sa.Column('localeCode', sa.VARCHAR(length=5), server_default=sa.text("'en'::character varying"), autoincrement=False, nullable=False),
    sa.Column('defaultEditor', sa.VARCHAR(length=255), server_default=sa.text("'markdown'::character varying"), autoincrement=False, nullable=False),
    sa.Column('lastLoginAt', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('dateFormat', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('appearance', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['providerKey'], ['authentication.key'], name='users_providerkey_foreign'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('providerKey', 'email', name='users_providerkey_email_unique'),
    postgresql_ignore_search_path=False
    )
    op.create_table('navigation',
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name='navigation_pkey')
    )
    op.create_table('userGroups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('groupId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['groupId'], ['groups.id'], name='usergroups_groupid_foreign', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='usergroups_userid_foreign', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='userGroups_pkey')
    )
    op.create_table('migrations_lock',
    sa.Column('index', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_locked', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('index', name='migrations_lock_pkey')
    )
    op.create_table('analytics',
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('isEnabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name='analytics_pkey')
    )
    op.create_table('renderers',
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('isEnabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name='renderers_pkey')
    )
    op.create_table('loggers',
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('isEnabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('level', sa.VARCHAR(length=255), server_default=sa.text("'warn'::character varying"), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name='loggers_pkey')
    )
    op.create_table('pageTags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pageId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tagId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pageId'], ['pages.id'], name='pagetags_pageid_foreign', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tagId'], ['tags.id'], name='pagetags_tagid_foreign', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pageTags_pkey')
    )
    op.create_table('apiKeys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expiration', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('isRevoked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('createdAt', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('updatedAt', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apiKeys_pkey')
    )
    op.create_table('pages',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('pages_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('isPrivate', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('isPublished', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('privateNS', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('publishStartDate', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('publishEndDate', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('render', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('toc', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('contentType', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('createdAt', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('updatedAt', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('editorKey', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('localeCode', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('authorId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creatorId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('extra', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['authorId'], ['users.id'], name='pages_authorid_foreign'),
    sa.ForeignKeyConstraint(['creatorId'], ['users.id'], name='pages_creatorid_foreign'),
    sa.PrimaryKeyConstraint('id', name='pages_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('pageTree',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('depth', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('isPrivate', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('isFolder', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('privateNS', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('parent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pageId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('localeCode', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('ancestors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pageId'], ['pages.id'], name='pagetree_pageid_foreign', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent'], ['pageTree.id'], name='pagetree_parent_foreign', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pageTree_pkey')
    )
    op.create_table('sessions',
    sa.Column('sid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('sess', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('expired', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('sid', name='sessions_pkey')
    )
    op.create_index('sessions_expired_index', 'sessions', ['expired'], unique=False)
    op.create_table('pageHistory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('isPrivate', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('isPublished', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('publishStartDate', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('publishEndDate', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=255), server_default=sa.text("'updated'::character varying"), autoincrement=False, nullable=True),
    sa.Column('pageId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contentType', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('createdAt', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('editorKey', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('localeCode', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('authorId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('versionDate', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('extra', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['authorId'], ['users.id'], name='pagehistory_authorid_foreign'),
    sa.PrimaryKeyConstraint('id', name='pageHistory_pkey')
    )
    op.create_table('authentication',
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('isEnabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('selfRegistration', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('domainWhitelist', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('autoEnrollGroups', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('strategyKey', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('displayName', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name='authentication_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('storage',
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('isEnabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('mode', sa.VARCHAR(length=255), server_default=sa.text("'push'::character varying"), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('syncInterval', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('state', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name='storage_pkey')
    )
    op.create_table('assets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('ext', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('kind', sa.TEXT(), server_default=sa.text("'binary'::text"), autoincrement=False, nullable=False),
    sa.Column('mime', sa.VARCHAR(length=255), server_default=sa.text("'application/octet-stream'::character varying"), autoincrement=False, nullable=False),
    sa.Column('fileSize', sa.INTEGER(), autoincrement=False, nullable=True, comment='In kilobytes'),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('createdAt', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('updatedAt', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('folderId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('authorId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint("kind = ANY (ARRAY['binary'::text, 'image'::text])", name='assets_kind_check'),
    sa.ForeignKeyConstraint(['authorId'], ['users.id'], name='assets_authorid_foreign'),
    sa.ForeignKeyConstraint(['folderId'], ['assetFolders.id'], name='assets_folderid_foreign'),
    sa.PrimaryKeyConstraint('id', name='assets_pkey')
    )
    op.create_table('groups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('pageRules', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('isSystem', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('createdAt', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('updatedAt', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('redirectOnLogin', sa.VARCHAR(length=255), server_default=sa.text("'/'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='groups_pkey')
    )
    op.create_table('brute',
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('firstRequest', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('lastRequest', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('lifetime', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('searchEngines',
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('isEnabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name='searchEngines_pkey')
    )
    op.create_table('assetData',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='assetData_pkey')
    )
    op.create_table('pageLinks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('localeCode', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('pageId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pageId'], ['pages.id'], name='pagelinks_pageid_foreign', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pageLinks_pkey')
    )
    op.create_index('pagelinks_path_localecode_index', 'pageLinks', ['path', 'localeCode'], unique=False)
    # ### end Alembic commands ###
