"""Database creation

Revision ID: 1368cfd732bb
Revises: e86dfd48920b
Create Date: 2025-02-05 21:55:22.196983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1368cfd732bb'
down_revision: Union[str, None] = 'e86dfd48920b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('vectors', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_id'), 'embedding', ['id'], unique=False)
    op.drop_table('embeddings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('folder_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('embedding', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='embeddings_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='embeddings_pkey')
    )
    op.drop_index(op.f('ix_embedding_id'), table_name='embedding')
    op.drop_table('embedding')
    # ### end Alembic commands ###
