"""Database vector pg  creation

Revision ID: 1c526ed0c5cb
Revises: 1368cfd732bb
Create Date: 2025-02-08 14:39:16.592934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c526ed0c5cb'
down_revision: Union[str, None] = '1368cfd732bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings_pg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('folder_name', sa.String(length=255), nullable=False),
    sa.Column('vectors', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embeddings_pg_id'), 'embeddings_pg', ['id'], unique=False)
    op.drop_index('ix_embedding_id', table_name='embedding')
    op.drop_table('embedding')
    # ### end Alembic commands ###


