global:
  scrape_interval: 15s  # Интервал сбора метрик (можно изменить)
  evaluation_interval: 15s

scrape_configs:
  - job_name: "fastapi"                # Название задачи (любое)
    metrics_path: "/metrics"           # Путь к метрикам (по умолчанию /metrics для инструмента prometheus-fastapi-instrumentator)
    scrape_interval: 5s               # Частота сбора метрик от FastAPI-сервиса
    static_configs:
      - targets: ["localhost:5001"]   # Адрес вашего приложения FastAPI (замените порт, если нужно)